### ISSUE TITLE
Exception thrown when using asset mapper

### ISSUE THREAD

**Issue by Arkounay** [artgris/FileManagerBundle#141]
## To reproduce:

Make a fresh new install, using symfony 6.4 or 7:

`symfony new sf6-test-install --webapp --version=6.4`

`composer require artgris/filemanager-bundle`

add routes `config/routes.yaml`

```yaml
artgris_bundle_file_manager:
    resource: "@ArtgrisFileManagerBundle/Controller"
    type:     attribute
    prefix:   /manager
```

add config/packages/file_manager.yaml
```yaml
artgris_file_manager:
    conf:
        default:
            dir: '%kernel.project_dir%/public/uploads'
```

mkdir `public/uploads`

now access with a browser the url `/manager/?conf=default`

An exception has been thrown during the rendering of a template ("Symfony\Component\AssetMapper\Compiler\JavaScriptImportPathCompiler::compile(): Return value must be of type string, null returned").
