### ISSUE TITLE
Wrong config service

### ISSUE THREAD

**Issue by Quovandius** [artgris/FileManagerBundle#18]
Hello,

I try to use the file manager and i have an error with my config.yml,

I have this configuration : 
```
artgris_file_manager:
    web_dir: web                 # set your public Directory (not required, default value: web)
    conf:
        default:
            dir: '%kernel.project_dir%/web/uploads'
            service: 'file_type_service'
```

And when i'll try to open manager in form view i have this error : 
Please define a "dir" or a "service" parameter in your config.yml

How can i fix this ?
