### ISSUE TITLE
CKEditor integration

### ISSUE THREAD

**Issue by WouterCypers** [artgris/FileManagerBundle#29]
I have a Symfony 4 project where I use [FOSCKEditorBundle](https://github.com/FriendsOfSymfony/FOSCKEditorBundle) in combination with FileManager. This might be interesting to add to the project?

In `manager.js`, under line 153, I added:

```javascript
// Module CKEditor
if (moduleName === 'ckeditor') {
    $('#form-multiple-delete').on('click', '.select', function () {
        var url = new URL(window.location.href);
        var funcNum = url.searchParams.get("CKEditorFuncNum");

        var fileUrl = $(this).attr("data-path");

        window.opener.CKEDITOR.tools.callFunction(funcNum, fileUrl);
        window.close();
    });
}
```
Example ckeditor config:

```yaml
fos_ck_editor:
    default_config: basic_config
    configs:
        basic_config:
            toolbar: basic_toolbar
        advanced_config:
            toolbar: advanced_toolbar
            filebrowserBrowseRoute: file_manager
            filebrowserBrowseRouteParameters:
                conf: files
                module: ckeditor
            filebrowserImageBrowseRoute: file_manager
            filebrowserImageBrowseRouteParameters:
                conf: images
                module: ckeditor
```
