### ISSUE TITLE
Image versions

### ISSUE THREAD

**Issue by ngrdanjski** [artgris/FileManagerBundle#54]
Hi, my config is:
```
conf:
        public:
            dir: "../public/uploads"
            tree: true
            upload:
                image_versions: {'': {crop: true, max_width: 10, max_height: 10}}
```

And on lists i my images are in orginal file. Maybe need to update a .twig file _list.html.twig do display image version/variation.

Tnx
