### ISSUE TITLE
Renaming an image without specifying its extension inside an "image" folder makes it disappear

### ISSUE THREAD

**Issue by Arkounay** [artgris/FileManagerBundle#79]
Here's my conf:
```yaml
artgris_file_manager:
  web_dir: public
  conf:
    default:
      dir: "../public/uploads/"
      type: image
```
If I upload an image there, and rename it without manually respecifying its extension:

![image](https://user-images.githubusercontent.com/9340719/97693381-61ee5c00-1aa1-11eb-8db4-8f2b1776c239.png)

![image](https://user-images.githubusercontent.com/9340719/97693445-77638600-1aa1-11eb-8811-632901bf0117.png)

it will disappear from the list because it's filtered out, since the list only accepts images.

the file will still be there and renamed properly however, just without any extension

![image](https://user-images.githubusercontent.com/9340719/97693742-e4771b80-1aa1-11eb-88f3-4e1d1a9ecd3d.png)

Is there any way to improve this ?

Thanks
